# NAME : RADHIKA PATWARI
# ROLL : 18CS10062

# COMMANDS : make clean
#			 make
#			 ./a.out

all:
	lex ass3_18CS10062.l
	gcc lex.yy.c ass3_18CS10062_main.c -lfl

ass3_18CS10062_main.c:
	touch ass3_18CS10062_main.c
	
clean:
	rm a.out lex.yy.c